## Part 1: Preprocessing

In [41]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [42]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [43]:
attrition_df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EnvironmentSatisfaction      int64
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
NumCompaniesWorked           int64
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [44]:
# Create y_df with the Attrition and Department columns

y_df = attrition_df[['Attrition', 'Department']].copy()
y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [45]:
# Create a list of at least 10 column names to use as X data
#"OverTime' was all zeros in training data so no point including it here

X = ['Education','Age','DistanceFromHome', 'JobSatisfaction','HourlyRate', 'EnvironmentSatisfaction','StockOptionLevel', 'WorkLifeBalance', 'YearsAtCompany', 'YearsSinceLastPromotion','NumCompaniesWorked']

# Create X_df using your selected columns
X_df = attrition_df[X]

# Show the data types for X_df
X_df.dtypes

Education                  int64
Age                        int64
DistanceFromHome           int64
JobSatisfaction            int64
HourlyRate                 int64
EnvironmentSatisfaction    int64
StockOptionLevel           int64
WorkLifeBalance            int64
YearsAtCompany             int64
YearsSinceLastPromotion    int64
NumCompaniesWorked         int64
dtype: object

In [46]:
X_df.nunique()

Education                   5
Age                        43
DistanceFromHome           29
JobSatisfaction             4
HourlyRate                 71
EnvironmentSatisfaction     4
StockOptionLevel            4
WorkLifeBalance             4
YearsAtCompany             37
YearsSinceLastPromotion    16
NumCompaniesWorked         10
dtype: int64

In [47]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=1)

In [48]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.fit_transform(X_test)


In [49]:
X_train_encoded

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [50]:
# Create a StandardScaler
# Fit the StandardScaler to the training data
scaler = StandardScaler().fit(X_train_encoded, X_test_encoded)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train_encoded)
X_train_scaled
X_test_scaled = scaler.transform(X_test_encoded)
X_test_scaled


array([[-0.35445508, -0.48235069, -0.81680533, ..., -0.24206921,
        -0.18898224, -0.18639148],
       [-0.35445508,  2.07318039, -0.81680533, ..., -0.24206921,
        -0.18898224, -0.18639148],
       [-0.35445508, -0.48235069,  1.22428192, ..., -0.24206921,
        -0.18898224, -0.18639148],
       ...,
       [-0.35445508,  2.07318039, -0.81680533, ..., -0.24206921,
        -0.18898224, -0.18639148],
       [-0.35445508, -0.48235069,  1.22428192, ..., -0.24206921,
        -0.18898224, -0.18639148],
       [-0.35445508,  2.07318039, -0.81680533, ..., -0.24206921,
        -0.18898224, -0.18639148]])

In [51]:
X_train_scaled.shape

(1102, 222)

In [52]:
y_df.dtypes

Attrition     object
Department    object
dtype: object

In [53]:
# Create a OneHotEncoder for the Department column
Department_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit the encoder to the training data
Department_encoded = Department_encoder.fit_transform(y_df[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_encoded_Department = Department_encoder.transform(y_train[['Department']])
y_train_encoded_Department
y_test_encoded_Department = Department_encoder.transform(y_test[['Department']])
y_test_encoded_Department

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [54]:
# # Created a StandardScaler for Department Column 
# # Fitted the StandardScaler to the y data
# scaler = StandardScaler().fit(y_train_encoded_Department, y_test_encoded_Department)

# # Scale the training and testing data
# y_train_scaled_Department = scaler.transform(y_train_encoded_Department)
# y_train_scaled_Department
# y_test_scaled_Department = scaler.transform(y_test_encoded_Department)
# y_test_scaled_Department

In [69]:
y_train_encoded_Department.shape

(1102, 3)

In [56]:
# Create a OneHotEncoder for the Attrition column
Attrition_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit the encoder to the training data
Attrition_encoded = Attrition_encoder.fit_transform(y_df[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_encoded_Attrition = Attrition_encoder.transform(y_train[['Attrition']])
y_train_encoded_Attrition
y_test_encoded_Attrition = Attrition_encoder.transform(y_test[['Attrition']])
y_test_encoded_Attrition

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.

In [57]:
# # Created a StandardScaler for Department Column 
# # Fitted the StandardScaler to the y data
# scaler = StandardScaler().fit(y_train_encoded_Attrition, y_test_encoded_Attrition)

# # Scale the training and testing data
# y_train_scaled_Attrition = scaler.transform(y_train_encoded_Attrition)
# y_train_scaled_Attrition
# y_test_scaled_Attrition = scaler.transform(y_test_encoded_Attrition)
# y_test_scaled_Attrition

In [58]:
y_train_scaled_Attrition.shape

(1102, 2)

## Create, Compile, and Train the Model

In [59]:
# Find the number of columns in the X training data
print(X_train_scaled.shape)


(1102, 222)


In [60]:
# #TESTING 
# from tensorflow.keras import layers, models, Model

# # Create the input layer
# input_layer = layers.Input(shape=(222,), name='input_features')  # Note the comma for a tuple shape

# # Create at least two shared layers
# shared_layer1 = layers.Dense(64, activation='relu', name='shared1')(input_layer)
# shared_layer2 = layers.Dense(32, activation='relu', name='shared2')(shared_layer1)

# # Create a branch for Department with a hidden layer and an output layer
# # Note: Use shared_layer2 for the department branch as intended
# Department_hidden = layers.Dense(64, activation='relu', name='department_hidden')(shared_layer2)
# Department_output = layers.Dense(1, activation='softmax', name='Department_output')(Department_hidden)

# # Create a branch for Attrition with a hidden layer and an output layer
# # Note: Use a separate hidden layer for the attrition branch
# Attrition_hidden = layers.Dense(64, activation='relu', name='attrition_hidden')(shared_layer2)
# Attrition_output = layers.Dense(1, activation='softmax', name='Attrition_output')(Attrition_hidden)  # Binary classification

# # Create the model
# model = Model(inputs=input_layer, outputs=[Department_output, Attrition_output])

# # Compile the model
# model.compile(optimizer='adam',
#               loss={'Department_output': 'binary_crossentropy',
#                     'Attrition_output': 'binary_crossentropy'},
#               metrics={'Department_output': 'accuracy',
#                        'Attrition_output': 'accuracy'})

# # Summarize the model
# model.summary()

# # Train the model
# batch_size = 32
# epochs = 10
# history = model.fit(
#     X_train_scaled,
#     {'Department_output': y_train_scaled_Department, 'Attrition_output': y_train_scaled_Attrition},
#     validation_data=(X_test_scaled, {'Department_output': y_test_scaled_Department, 'Attrition_output': y_test_scaled_Attrition}),
#     epochs=epochs,
#     batch_size=batch_size
# )

In [61]:
from tensorflow.keras import layers, models, Model

# Create the input layer
input_layer = layers.Input(shape=(X_train_scaled.shape[1],), name='input_features') # is this incorrect? Should it be dense = layers.Dense(64,activation="relu") 
#input_layers = dense(inputs) as shown in Functional API documentation in Lesson 19.3 video

# Create at least two shared layers
shared_layer1 = layers.Dense(64, activation='relu',name='shared1')(input_layer)
shared_layer2 = layers.Dense(32, activation='relu',name='shared2')(shared_layer1)

In [62]:
#Preparing Data for Output layers
# columns related to the Department in the training data
y_train_Department = y_train[[col for col in y_train.columns if 'Department' in col]]

# Repeat this for the following in the training data
# Attrition
y_train_Attrition = y_train[[col for col in y_train.columns if 'Attrition' in col]]


In [63]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
Department_hidden = layers.Dense(64, activation='relu',name='department_hidden')(shared_layer2)   # should this be shared layer 1 and attrition one as shared layer 2?


# Create the output layer
Department_output = layers.Dense(len(y_train_Department.columns),
                           activation='softmax',
                             name='Department_output')(Department_hidden)


In [64]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
Attrition_hidden = layers.Dense(64, activation='relu',name='attrition_hidden')(shared_layer2)

# Create the output layer
Attrition_output = layers.Dense(len(y_train_Attrition.columns),
                           activation='softmax',
                             name='Attrition_output')(Attrition_hidden)


In [65]:
# Create the model
model = Model(inputs=input_layer, outputs=[
    Department_output,
    Attrition_output
])

# Compile the model
model.compile(optimizer='adam',
              loss={'Department_output': 'categorical_crossentropy',
                    'Attrition_output': 'binary_crossentropy'},
              metrics={'Department_output': 'accuracy',
                       'Attrition_output': 'accuracy'})

# Summarize the model
model.summary()


Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_features      │ (None, 222)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared1 (Dense)     │ (None, 64)        │     14,272 │ input_features[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared2 (Dense)     │ (None, 32)        │      2,080 │ shared1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_hidden   │ (None, 64)        │      2,112 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden    │ (None, 64)        │      2,112 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Department_output   │ (None, 1)         │         65 │ department_hidde… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Attrition_output    │ (None, 1)         │         65 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 20,706 (80.88 KB)

 Trainable params: 20,706 (80.88 KB)

 Non-trainable params: 0 (0.00 B)

In [68]:
# Train the model
# model.fit(
#     X_train_scaled,
#     {
#         'Department_output': y_train_scaled_Department,
#         'Attrition_output': y_train_scaled_Attrition
#     },
#     epochs=10,  # You can adjust the number of epochs based on your needs
#     batch_size=32,  # You can adjust the batch size based on your available memory
#     validation_split=0.2  # You can specify the validation split if you have a separate validation set
# )


# should this be based on basic cnn model activity 19.2.1? i.e. 

batch_size = 32
epochs = 10
history = model.fit(
    X_train_scaled, {'Department_output': y_train_encoded_Department,'Attrition_output':y_train_encoded_Attrition},
    # validation_data=(X_test_scaled, (y_test_encoded_Department,y_test_encoded_Attrition)),
    epochs=epochs
)



Epoch 1/10


ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 3), output.shape=(None, 1)

In [ ]:
# Train the model


In [ ]:
# Evaluate the model with the testing data
results = model.evaluate(np.array(X_test), {
        'Department_output': y_test_Department,
        'Attrition_output': y_test_Attrition
    })

In [ ]:
# Evaluate the model with the testing data


In [ ]:
# Print the accuracy for both department and attrition


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. 
2. 
3. 